dist: bionic

language: minimal

env:
  global:
    - REPO=docksal/solr

  matrix:
    - VERSION=5.5 FROM=solr:5.5.5-slim SOLR_DEFAULT_CONFIG_SET=search_api_solr_8.x-1.2
    - VERSION=6.6 FROM=solr:6.6.5-slim SOLR_DEFAULT_CONFIG_SET=search_api_solr_8.x-2.0
    - VERSION=7.5 FROM=solr:7.5.0-slim SOLR_DEFAULT_CONFIG_SET=search_api_solr_8.x-2.0
    - VERSION=7.7 FROM=solr:7.7.1-slim SOLR_DEFAULT_CONFIG_SET=search_api_solr_8.x-2.0
    - VERSION=8.1 FROM=solr:8.1.1-slim SOLR_DEFAULT_CONFIG_SET=search_api_solr_8.x-3.0

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - make
  - make test

after_success:
  - make release

after_failure:
  - make logs
