language: bash

services:
  - docker

env:
  matrix:
    - SOLR_VER=7.5.0 TAGS=7.5,7,latest
    - SOLR_VER=6.6.5 TAGS=6.6,6
    - SOLR_VER=5.5.5 TAGS=5.5,5
    - SOLR_VER=4.10.4 TAGS=4.10,4
    - SOLR_VER=3.6.2 TAGS=3.6,3

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
